# Generated by Django 3.2.6 on 2021-09-05 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0002_auto_20210905_1328'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='fullname',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='nombre completo'),
        ),
    ]
