# Generated by Django 3.2.6 on 2021-09-05 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departamentos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departamento',
            name='anulate',
            field=models.BooleanField(default=False, verbose_name='Anulado'),
        ),
    ]
